version: "3.9"

services:
  web:
    build:
      context: /monitoring_system
    working_dir: /app/app
    command: gunicorn --workers=1 app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/monitoring_system/app/static
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    build: /nginx
    volumes:
      - static_volume:/monitoring_system/app/static
    ports:
      - 80:80
    depends_on:
      - web
      
  redis:
    image: "redis:7.0.5-alpine"
    volumes:
      - redis:/data
    expose:
      - 6379

volumes:
  static_volume:
  redis: