version: "3.9"

services:
  web:
    build:
      context: /monitoring_system
    image: wsms_django
    command: /start
    working_dir: /app/app
    command: gunicorn --workers=1 app.wsgi:application --bind 0.0.0.0:8000 && python -m celery -A app worker -l info
    volumes:
      - static_volume:/monitoring_system/app/static
    ports:
      - 8000:8000
    env_file:
      - .env-sample
    depends_on:
      - redis
      - db
      
  celery_worker:
    build:
      context: /monitoring_system
    image: wsms_celery_worker
    command: /start-celeryworker
    volumes:
      - static_volume:/monitoring_system/app/static
    env_file:
      - .env-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: /monitoring_system
    image: wsms_celery_beat
    command: /start-celerybeat
    volumes:
      - static_volume:/monitoring_system/app/static
    env_file:
      - .env-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: /monitoring_system
    image: wsms_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

  nginx:
    build: /nginx
    volumes:
      - static_volume:/monitoring_system/app/static
    depends_on:
      - web
      
  redis:
    image: "redis:7.0.5-alpine"
    volumes:
      - redis:/data
    ports:
      - 6379:6379
      
  db:
    image: "postgres:14.5-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-sample

volumes:
  static_volume:
  redis:
  postgres_data: