version: "3.9"

services:
  web:
    build:
      context: /django_inspector
    command: gunicorn --workers=1 django_inspector.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/django_inspector/staticfiles
    expose:
      - 8000
    env_file:
      - .env-sample
    depends_on:
      - redis
      - db
      
  celery_worker:
    restart: always
    build:
      context: ./django_inspector
    command: celery -A django_inspector worker -l info
    volumes:
      - static_volume:/django_inspector/staticfiles
    env_file:
      - .env-sample
    depends_on:
      - redis
      - db
      - web
      
  celery_beat:
    restart: always
    build:
      context: ./django_inspector
    command: celery -A django_inspector beat -l info
    volumes:
      - static_volume:/django_inspector/staticfiles
    env_file:
      - .env-sample
    depends_on:
      - redis
      - db
      - web

  nginx:
    build: /nginx
    volumes:
      - static_volume:/django_inspector/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
      
  redis:
    image: "redis:7.0.5-alpine"
    volumes:
      - redis:/data
    ports:
      - 6379:6379
      
  db:
    image: "postgres:14.5-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-sample
    expose:
      - 5432

volumes:
  static_volume:
  app:
  redis:
  postgres_data: