# Generated by Django 4.1.1 on 2022-10-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webserver',
            name='name',
            field=models.CharField(help_text='For example: My personal blog', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='webserver',
            name='status',
            field=models.CharField(choices=[('H', 'Healthy'), ('U', 'Unhealthy')], default='H', help_text='Default: healthy', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='webserver',
            name='url',
            field=models.URLField(help_text='For example: https://google.com', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='webserverrequest',
            name='latency',
            field=models.PositiveSmallIntegerField(verbose_name='Latency in seconds'),
        ),
        migrations.AlterField(
            model_name='webserverrequest',
            name='started_at',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='webserverrequest',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], default='S', max_length=1, verbose_name='Status'),
        ),
    ]
