# Generated by Django 4.1.1 on 2022-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_webserver_name_alter_webserver_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webserver',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, the system will check the status of the web server', verbose_name='Is enabled'),
        ),
    ]
