# Generated by Django 4.1.1 on 2022-10-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_webserver_is_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webserver',
            options={'verbose_name': 'Web server', 'verbose_name_plural': 'Web servers'},
        ),
    ]
