# Generated by Django 4.1.1 on 2022-10-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_webserver_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webserverrequest',
            old_name='webserver',
            new_name='web_server',
        ),
    ]
