# Generated by Django 4.1.1 on 2022-10-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='If enabled, the system will check the status of the web server', verbose_name='Is enabled')),
                ('name', models.CharField(help_text='For example: My personal blog', max_length=100, verbose_name='Name')),
                ('url', models.URLField(help_text='For example: https://google.com', verbose_name='URL')),
                ('status', models.CharField(choices=[('H', 'Healthy'), ('U', 'Unhealthy')], default='H', help_text='Default: healthy', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Web server',
                'verbose_name_plural': 'Web servers',
            },
        ),
        migrations.CreateModel(
            name='WebServerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Start time')),
                ('latency', models.PositiveSmallIntegerField(verbose_name='Latency in seconds')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Response status code')),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], default='S', max_length=1, verbose_name='Status')),
                ('web_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.webserver')),
            ],
            options={
                'verbose_name': 'Web server request',
                'verbose_name_plural': 'Web server requests',
            },
        ),
    ]
